### ISSUE TITLE
Arcane Knowledge rules muddle: how many spells can be memorised? 

### ISSUE THREAD

**Issue by Unclebaby** [raleel/cfi-srd#15]
In CFI the skill Arcane Knowledge says it determines spells in memory but the rank table bases it all on INT and Rank.

![image](https://github.com/raleel/cfi-srd/assets/25222758/b4542a8f-1ef6-4e9b-8d18-f9ba584ba9e0)

![image](https://github.com/raleel/cfi-srd/assets/25222758/a7f8f309-f1ae-42f9-ba9f-5d6e215ab46a)

**Comment by raleel** [comment]
The arcane knowledge text is actually wrong. It determines how many spells you start with

"A mage begins with knowledge of the Rank 0 cantrip Read Magic, as well as two cantrips (Rank 0) for every 1/10th Arcane Knowledge (skill x 0.1). If the mage qualifies as Rank 1, they also know one Rank 1 spell for every 1/10th Arcane Knowledge."

**Comment by Unclebaby** [comment]
I'll change this to...

_It also determines the number of starting spells the caster may have - covered in more detail in the Mage class's [Rank Structure](0003_Classes.md?id=rank-structure-2) section._
