### ISSUE TITLE
Tables without headers? 

### ISSUE THREAD

**Issue by Unclebaby** [raleel/cfi-srd#84]
Normally, in GH Markdown the first row is bolded to help make a clear header. 
This can look weird where there is no header.

A blank header could be placed instead where a table's content has none.

##### Table with default header row (row 1)

| **Rank:** Cleric 5, Mage 5 | **Casting Time:** 2 Actions |
| :-- | :-- |
| **Sphere:** Astral | **Duration:** See Below |
| **Cost:** 3 +1/additional Intensity | **Range:** Touch |
| **Area:** See Below | **Resist:** N/A |

##### Table with blank  header

|||
| :-- | :-- |
| **Rank:** Cleric 2 | **Casting Time:** 2 Actions |
| **Sphere:** Guardian | **Duration:** See Below |
| **Cost:** 3, +1/additional Intensity | **Range:** 360 ft |
| **Area:** 15 ft. Radius | **Resist:** See Below |

If you ask it of me I will do it.

**Comment by raleel** [comment]
Blank header is best header

**Comment by Unclebaby** [comment]
Done
